### ISSUE TITLE
DBuzz posts rendering issue

### ISSUE THREAD

**Issue by hiveuprss** [ecency/render-helper#11]
On Ecency mobile, some DBuzz posts are rendering with the image IPFS markdown text as the title of the post. 

For example https://ecency.com/hive-193084/@luueetang/ilgehnemnyhicj7pja1jye

![97876940-2AF1-4F07-994C-8D7FB13362F0](https://user-images.githubusercontent.com/62359919/117914312-ef540980-b297-11eb-9f17-6ec2f367e79e.jpeg)

**Comment by feruzm** [comment]
@hiveuprss thanks for report, that's because dbuzz app sets title of post as such. Should report to dbuzz developers so they set title to something else or set first word from content rather than link of image.

**Comment by hiveuprss** [comment]
Ahh good point. You’re right it must be fixed in DBuzz side.

**Comment by hiveuprss** [comment]
Reported in DBuzz discord

**Comment by feruzm** [comment]
Great, 👍  Thank you, hope they will fix it. This was reported few times.
